# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "PowerShell Module / Create artifact"
on:
    workflow_dispatch:

jobs:
    create-artifact:
        name: "Create module artifact"
        runs-on: ubuntu-latest

        env:
            EVENT_TYPE: ${{ github.event_name }}
            TAG_NAME: ${{ github.ref_name }}

        steps:
            -   name: "Generate artifact tag value"
                shell: pwsh
                run: |
                    "ARTIFACT_TAG=$($env:EVENT_TYPE -eq "push" ? $env:TAG_NAME : $([datetime]::Now.ToString("yyyyMMddTHHmmss")))" | Out-File -FilePath $env:GITHUB_ENV -Append

            -   name: "Checkout GitHub Action"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
        
            -   name: "Setup .NET SDK"
                uses: actions/setup-dotnet@v3
                with:
                  global-json-file: global.json

            -   name: "Install PlatyPS PowerShell module"
                shell: pwsh
                run: |
                    Install-Module -Name "PlatyPS" -Force

            -   name: "Restore class library project"
                shell: pwsh
                run: |
                    dotnet restore ./src/Lib

            -   name: "Build module"
                shell: pwsh
                run: |
                    ./build.ps1

            -   name: "Upload artifact"
                uses: actions/upload-artifact@v3
                with:
                    name: "SmallsOnline.TeamsAttendance.Pwsh_${{ env.ARTIFACT_TAG }}"
                    path: "./out/*"