# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "PowerShell Module / Publish module"
on:
    push:
        tags: [ 'v*.*.*', 'v*.*.*-*' ]
    workflow_dispatch:

jobs:
    publish-module:
        name: "Publish module to PSGallery"
        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout GitHub Action"
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: "Setup PowerShell 7.3"
                shell: bash
                run: |
                    sudo apt-get update
                    sudo apt-get install -y wget apt-transport-https software-properties-common
                    wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
                    sudo dpkg -i packages-microsoft-prod.deb
                    rm packages-microsoft-prod.deb
                    sudo apt-get update
                    sudo apt-get install -y powershell
        
            -   name: "Setup .NET SDK"
                uses: actions/setup-dotnet@v3
                with:
                  global-json-file: global.json

            -   name: "Install PlatyPS PowerShell module"
                shell: pwsh
                run: |
                    Install-Module -Name "PlatyPS" -Force

            -   name: "Install required modules"
                shell: pwsh
                run: |
                    ./installRequiredModules.ps1

            -   name: "Restore class library project"
                shell: pwsh
                run: |
                    dotnet restore ./src/Lib

            -   name: "Build module"
                shell: pwsh
                run: |
                    ./build.ps1

            -   name: "Publish to PSGallery"
                shell: pwsh
                working-directory: 
                run: |
                    Publish-Module -Path "./build/SmallsOnline.TeamsAttendance.Pwsh/" -NuGetApiKey "${{ secrets.PSGALLERY_KEY }}" -Repository "PSGallery"